### ISSUE TITLE
incorrect contract source code

### ISSUE THREAD

**Issue by bojanterzic529** [cleveragentfinance/contract#4]

**Comment by bojanterzic529** [comment]
hi, I found an issue in contract source code

**Comment by FlextraApe** [comment]
What's the problem exactly?

> hi, I found an issue in contract source code

What's the problem exactly?

**Comment by flextra19** [comment]
> hi, I found an issue in contract source code

What's the problem exactly?

**Comment by bojanterzic529** [comment]
function availableDeposit(uint256 _amount) public pure returns (uint256) {
        return type(uint128).max;
    }

    function availableWithdraw(uint256 _amount) public pure returns (uint256) {
        return type(uint128).max;
    }
here, why is there unused value here?

**Comment by flextra19** [comment]
> ```
> function availableDeposit(uint256 _amount) public pure returns (uint256) {
>     return type(uint128).max;
> }
> 
> function availableWithdraw(uint256 _amount) public pure returns (uint256) {
>     return type(uint128).max;
> }
> ```
> 
> here, why is there unused value here?

This is just code template.

**Comment by bojanterzic529** [comment]
ah, okay, got it

**Comment by flextra19** [comment]
import "@openzeppelin/contracts/utils/Address.sol";
import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/math/SafeMath.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";
import "@uniswap/v2-periphery/contracts/interfaces/IUniswapV2Router02.sol";

IUniswapV2Router02.sol is using different compile version with other contracts, and this can make warning while compile on hardhat.  How can we solve this problem?
